# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from key_publisher_msgs/key_publisher_msgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class key_publisher_msgs(genpy.Message):
  _md5sum = "c153bb0a32a052ad0d10173dacb72523"
  _type = "key_publisher_msgs/key_publisher_msgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool move_left
bool move_right
bool move_up
bool move_down
bool move_upward
bool move_downward
bool move_forward
bool move_backward
bool move_angle_insertion
bool move_angle_retraction
bool large_gain
bool small_gain
bool small_push
"""
  __slots__ = ['move_left','move_right','move_up','move_down','move_upward','move_downward','move_forward','move_backward','move_angle_insertion','move_angle_retraction','large_gain','small_gain','small_push']
  _slot_types = ['bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       move_left,move_right,move_up,move_down,move_upward,move_downward,move_forward,move_backward,move_angle_insertion,move_angle_retraction,large_gain,small_gain,small_push

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(key_publisher_msgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.move_left is None:
        self.move_left = False
      if self.move_right is None:
        self.move_right = False
      if self.move_up is None:
        self.move_up = False
      if self.move_down is None:
        self.move_down = False
      if self.move_upward is None:
        self.move_upward = False
      if self.move_downward is None:
        self.move_downward = False
      if self.move_forward is None:
        self.move_forward = False
      if self.move_backward is None:
        self.move_backward = False
      if self.move_angle_insertion is None:
        self.move_angle_insertion = False
      if self.move_angle_retraction is None:
        self.move_angle_retraction = False
      if self.large_gain is None:
        self.large_gain = False
      if self.small_gain is None:
        self.small_gain = False
      if self.small_push is None:
        self.small_push = False
    else:
      self.move_left = False
      self.move_right = False
      self.move_up = False
      self.move_down = False
      self.move_upward = False
      self.move_downward = False
      self.move_forward = False
      self.move_backward = False
      self.move_angle_insertion = False
      self.move_angle_retraction = False
      self.large_gain = False
      self.small_gain = False
      self.small_push = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13B().pack(_x.move_left, _x.move_right, _x.move_up, _x.move_down, _x.move_upward, _x.move_downward, _x.move_forward, _x.move_backward, _x.move_angle_insertion, _x.move_angle_retraction, _x.large_gain, _x.small_gain, _x.small_push))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.move_left, _x.move_right, _x.move_up, _x.move_down, _x.move_upward, _x.move_downward, _x.move_forward, _x.move_backward, _x.move_angle_insertion, _x.move_angle_retraction, _x.large_gain, _x.small_gain, _x.small_push,) = _get_struct_13B().unpack(str[start:end])
      self.move_left = bool(self.move_left)
      self.move_right = bool(self.move_right)
      self.move_up = bool(self.move_up)
      self.move_down = bool(self.move_down)
      self.move_upward = bool(self.move_upward)
      self.move_downward = bool(self.move_downward)
      self.move_forward = bool(self.move_forward)
      self.move_backward = bool(self.move_backward)
      self.move_angle_insertion = bool(self.move_angle_insertion)
      self.move_angle_retraction = bool(self.move_angle_retraction)
      self.large_gain = bool(self.large_gain)
      self.small_gain = bool(self.small_gain)
      self.small_push = bool(self.small_push)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13B().pack(_x.move_left, _x.move_right, _x.move_up, _x.move_down, _x.move_upward, _x.move_downward, _x.move_forward, _x.move_backward, _x.move_angle_insertion, _x.move_angle_retraction, _x.large_gain, _x.small_gain, _x.small_push))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.move_left, _x.move_right, _x.move_up, _x.move_down, _x.move_upward, _x.move_downward, _x.move_forward, _x.move_backward, _x.move_angle_insertion, _x.move_angle_retraction, _x.large_gain, _x.small_gain, _x.small_push,) = _get_struct_13B().unpack(str[start:end])
      self.move_left = bool(self.move_left)
      self.move_right = bool(self.move_right)
      self.move_up = bool(self.move_up)
      self.move_down = bool(self.move_down)
      self.move_upward = bool(self.move_upward)
      self.move_downward = bool(self.move_downward)
      self.move_forward = bool(self.move_forward)
      self.move_backward = bool(self.move_backward)
      self.move_angle_insertion = bool(self.move_angle_insertion)
      self.move_angle_retraction = bool(self.move_angle_retraction)
      self.large_gain = bool(self.large_gain)
      self.small_gain = bool(self.small_gain)
      self.small_push = bool(self.small_push)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13B = None
def _get_struct_13B():
    global _struct_13B
    if _struct_13B is None:
        _struct_13B = struct.Struct("<13B")
    return _struct_13B
